### ISSUE TITLE
Multi-author sites show incorrect authorship

### ISSUE THREAD

**Issue by fluffy-critter** [alltogethernow/web#15]
**Describe the bug**

On multi-author sites such as arstechnica.com, the entire site is shown as being the most recent author's identity, and even applying their attribution to all articles from the site. 

For example, at the time of this writing, the most recent article on arstechnica.com was written by Kiona N. Smith, and so *all* arstechnica articles are showing up as her.

**To Reproduce**

1. subscribe to a multi-author site

**Expected Behavior**

Expected behavior should be that the article appears as belonging to the site itself, and that the authorship of the individual articles be the actual author of said articles.

**Screenshots**

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/347162/63967739-e33c0000-ca52-11e9-88fc-76b97c715945.png">

**Browser(please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 12.1.2

**Comment by fluffy-critter** [comment]
By point of comparison, here's how it looks in FeedOnFeeds:

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/347162/63967965-63626580-ca53-11e9-8baa-2e0e07a616d4.png">

Note how the site itself maintains its own name/title, and each individual article has the correct author byline on its header.

**Comment by grantcodes** [comment]
Oops typed the wrong issue number in the commit but this is fixed in 3.7.5
