### ISSUE TITLE
Blank screen after login

### ISSUE THREAD

**Issue by cs224** [alltogethernow/web#21]
**Describe the bug**
I did not use alltogethernow for a couple of weeks, but tried to login today. I get a blank screen after login. It is completely white.

**To Reproduce**
I login via https://weisser-zwerg.dev and I use aperture as MicroSub server.

**Browser(please complete the following information):**
 - OS: iOS and Linux
 - Browser safari and chrome

**More Info**
In the dev console of chrome I see:

> Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at Ns (react-dom.production.min.js:4764)
    at Object.enqueueSetState (react-dom.production.min.js:2840)
    at t.setState (react.production.min.js:60)
    at react-router.js:59
    at n (history.js:162)
    at history.js:180
    at Array.forEach (<anonymous>)
    at Object.notifyListeners (history.js:179)
    at A (history.js:300)
    at history.js:414

**Comment by grantcodes** [comment]
Yep I broke stuff.

Should be working with the new version, you may need to delete browser caches
